apiVersion: v1
kind: ConfigMap
metadata:
  name: #{service}#-configmap
  namespace: #{namespace}#
data:
  APP_ENV: "#{env}#"
  APP_NAME: "#{service}#"
  PG_HOST: "#{PG_HOST}#"
  PG_PORT: "#{PG_PORT}#"
  PG_USER: "#{PG_USER}#"
  PG_DATABASE: "#{PG_DATABASE}#"
  EMBEDDING_MODE: "#{EMBEDDING_MODE}#"
  SQL_FILES: "#{SQL_FILES}#"
  LLM_PROVIDER: "#{LLM_PROVIDER}#"
