apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: #{service}#-hpa
  namespace: #{namespace}#
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{service}#-deployment
  minReplicas: #{ms-replicas}#
  maxReplicas: #{ms-max-replicas}#
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: #{target-cpu}#
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: #{target-memory}#
